### ISSUE TITLE
UITableView的bottom_attr与bottom_attr_safe约束

### ISSUE THREAD

**Issue by dkdsj** [suruihai/NSLayoutConstraint-SSLayout#3]
你好 我现在用NSLayoutConstraint-SSLayout来布局，有个疑问
1. 用self.view.bottom_attr_safe 这样写tableview的内容会被iPhoneX底部安全区域遮挡
[self.mineTableView activateConstraints:^{
        [self.mineTableView.top_attr equalTo:self.view.top_attr_safe constant:0] ;
        self.mineTableView.leading_attr = self.view.leading_attr_safe;
        self.mineTableView.bottom_attr = self.view.bottom_attr_safe;
        self.mineTableView.trailing_attr = self.view.trailing_attr_safe;
    }];
用self.view.bottom_attr不会被遮挡 是这样吗

**Comment by suruihai** [comment]
用self.view.bottom_attr_safe，应该不会被遮挡，因为都是相对safeArea做布局

**Comment by dkdsj** [comment]
> 用self.view.bottom_attr_safe，应该不会被遮挡，因为都是相对safeArea做布局

**Comment by dkdsj** [comment]
ok 我再看看
